'use strict';

// tests for dequeue
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('dequeue', '//handlers/mail-handlers/dequeue.js', 'handler');

describe('dequeue', () => {
  //Test Object
  let data;

  //Composed Message taken from SQS Queue. 
  before(() => {
    data = {
      Records: [{
        messageId: 'FILL_IN',
        receiptHandle: 'FILL_IN',
        body: '{"Destination":"demo@gmail.com","Title":"Demo","Text":"Demo demo.","Sender":"demo@live.com"}',
        attributes: [Object],
        messageAttributes: {},
        md5OfBody: 'FILL_IN',
        eventSource: 'aws:sqs',
        eventSourceARN: 'arn:aws:sqs:us-east-1:FILL_IN:MailQueue',
        awsRegion: 'us-east-1'
      }]
    }
  });

  it('Test Dequeue', async () => {
    const response = await wrapped.run(data);
      expect(response).to.be.empty;
  });
});