'use strict';

// tests for queue
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('queue', '//handlers/mail-handlers/queue.js', 'handler');

describe('queue', () => {
  let data;

  before(() => {
    data = {
      destination: "Demo@gmail.com",
      title: "Demo",
      text: "Demo demo.",
      sender: "Demo@live.com"
    }  
  });

  it('Test Queue', async () => {
    const response = await wrapped.run(data);
      expect(response).to.be.empty;
  });
});